In [16]:
import pandas as pd
import numpy as np
from sklearn import datasets
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
import seaborn as sb
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [17]:
dfX = pd.read_csv('X.csv')
X = dfX
dfX.tail()

-0.00610163036267645  -0.00564772162352118  -0.00507088179350626  \
138234              -1.57829             -2.560223             -2.343307   
138235              -1.57829             -2.560223             -2.343307   
138236              -1.57829             -2.560223             -2.343307   
138237              -1.57829             -2.560223             -2.343307   
138238              -1.57829             -2.560223             -2.343307   

        -0.00438659439707201  -0.00361285934965876  -0.00276939069510669  \
138234             -1.021847              0.818866              2.368043   
138235             -1.021847              0.818866              2.368043   
138236             -1.021847              0.818866              2.368043   
138237             -1.021847              0.818866              2.368043   
138238             -1.021847              0.818866              2.368043   

        -0.00187364521764144  -0.000943666044049693  -3.78393687416748e-07  \
138234              2.944985               2.276026               0.607649   
138235              2.944985               2.276026               0.607649   
138236              2.944985               2.276026               0.607649   
138237              2.944985               2.276026               0.607649   
138238              2.944985               2.276026               0.607649   

        0.000932703555318616  ...  0.0112478879601723  0.0298194964778406  \
138234             -1.378798  ...             0.57913            0.415212   
138235             -1.378798  ...             0.57913            0.415212   
138236             -1.378798  ...             0.57913            0.415212   
138237             -1.378798  ...             0.57913            0.415212   
138238             -1.378798  ...             0.57913            0.415212   

        -0.0258038130206867  0.0175522635535516  0.0233655194044791  \
138234             0.178667           -0.148418           -0.248931   
138235             0.178667           -0.148418           -0.248931   
138236             0.178667           -0.148418           -0.248931   
138237             0.178667           -0.148418           -0.248931   
138238             0.178667           -0.148418           -0.248931   

        0.0275976151612154  0.0420507515859686  0.0176488661748403  \
138234           -0.258957           -0.145863            0.075973   
138235           -0.258957           -0.145863            0.075973   
138236           -0.258957           -0.145863            0.075973   
138237           -0.258957           -0.145863            0.075973   
138238           -0.258957           -0.145863            0.075973   

        0.0445178194231775  0.0199181759668705  
138234            0.188391            0.253562  
138235            0.188391            0.253562  
138236            0.188391            0.253562  
138237            0.188391            0.253562  
138238            0.188391            0.253562  

[5 rows x 40 columns]

In [18]:
dfy = pd.read_csv('y.csv')
y = dfy
dfy.head()

1
0  1
1  1
2  1
3  0
4  1

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [20]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)

In [21]:
clf.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'random_state': None,
 'splitter': 'best'}

In [22]:
X_test

-0.00610163036267645  -0.00564772162352118  -0.00507088179350626  \
51403               0.084134              0.066056              0.041073   
81870              -0.225505             -0.196090             -0.193774   
115679              0.100576              0.098376              0.088099   
42150               0.455458              0.240662              0.029095   
85715             -12.704510            -12.899348            -13.122892   
...                      ...                   ...                   ...   
91683              -0.051251             -0.076270             -0.079950   
34740              -6.229517             -6.211799             -6.196923   
83987              -0.457535             -1.101999             -1.705676   
137666              2.110820              2.785742              2.490570   
3219              -20.127915            -20.145999            -20.164087   

        -0.00438659439707201  -0.00361285934965876  -0.00276939069510669  \
51403               0.040102              0.064960              0.063580   
81870              -0.195297             -0.160015             -0.127256   
115679              0.081946              0.057486              0.029103   
42150              -0.070033             -0.008068              0.173228   
85715             -13.360640            -13.602043            -13.829107   
...                      ...                   ...                   ...   
91683              -0.082463             -0.102114             -0.098003   
34740              -6.188499             -6.187175             -6.190036   
83987              -2.243288             -2.691777             -3.031116   
137666              1.314365             -0.358572             -1.977353   
3219              -20.182185            -20.200307            -20.218437   

        -0.00187364521764144  -0.000943666044049693  -3.78393687416748e-07  \
51403               0.031533               0.001454              -0.017396   
81870              -0.105213              -0.124883              -0.126120   
115679              0.037520               0.067247               0.070180   
42150               0.363147               0.445020               0.361325   
85715             -14.025026             -14.189573             -14.318603   
...                      ...                    ...                    ...   
91683              -0.084550              -0.076187              -0.061375   
34740              -6.191739              -6.186780              -6.177132   
83987              -3.245760              -3.325192              -3.264679   
137666             -3.018558              -3.131161              -2.275418   
3219              -20.236562             -20.254698             -20.272861   

        0.000932703555318616  ...  0.0112478879601723  0.0298194964778406  \
51403              -0.005770  ...            0.044116           -0.039869   
81870              -0.169871  ...           -0.175847           -0.188577   
115679              0.054008  ...            5.883873            7.110370   
42150               0.145369  ...            0.196526            0.149698   
85715             -14.409196  ...          -14.077676          -14.181880   
...                      ...  ...                 ...                 ...   
91683              -0.077823  ...           -0.066946           -0.123077   
34740              -6.169382  ...           -6.202644           -6.235851   
83987              -3.065693  ...           -2.413148           -2.403458   
137666             -0.736505  ...            0.000000           10.000000   
3219              -20.291031  ...          -20.877070          -20.882074   

        -0.0258038130206867  0.0175522635535516  0.0233655194044791  \
51403             -0.153673           -0.377600           -0.732299   
81870             -0.187134           -0.148568           -0.213312   
115679             8.162155            8.934709            9.532690   
42150              0.059806         

In [23]:
predictions = clf.predict(X_test)
predictions

array([0, 1, 1, ..., 1, 1, 1], dtype=int64)

In [24]:
# show difference between tree that doesn't have stopping criteria and the one
# that does
clf.predict_proba(X_test)

array([[0.76470588, 0.23529412],
       [0.42857143, 0.57142857],
       [0.26666667, 0.73333333],
       ...,
       [0.18181818, 0.81818182],
       [0.07692308, 0.92307692],
       [0.41666667, 0.58333333]])

In [25]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, predictions)

0.6962287808641975

In [26]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, predictions, labels=[0,1])

array([[14473,  5926],
       [ 6672, 14401]], dtype=int64)

In [27]:
from sklearn.metrics import precision_score
precision_score(y_test, predictions)

0.7084665715550745

In [28]:
from sklearn.metrics import recall_score
recall_score(y_test, predictions)

0.6833863237317895

In [29]:
from sklearn.metrics import classification_report

print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.68      0.71      0.70     20399
           1       0.71      0.68      0.70     21073

    accuracy                           0.70     41472
   macro avg       0.70      0.70      0.70     41472
weighted avg       0.70      0.70      0.70     41472



In [30]:
confusion_matrix(y_test, predictions)

array([[14473,  5926],
       [ 6672, 14401]], dtype=int64)